db.zoologico.drop()
db.zoologico.insertMany([
        {
 
         especie:"gorila",
         etiqueta:"mamiferos",
         familia:"hominidae",
         duracion:35,
         alimentación:{
                 tipo:"herbivoro", 
                 comida:["brotes","hojas"]},
         habitat:"bosque tropical",
         secciones:"galeria",
         cantidad:13 },
 
 
         {   especie:"chimpance",etiqueta:"mamiferos",familia:"hominidae",duracion:39,alimentación:{tipo:"herbivoro", comida:["frutos","hojas"]},habitat:"bosque tropical",secciones:"galeria", cantidad:8 },
         {   especie:"mandril",etiqueta:"mamiferos",familia:"cercopithecidae",duracion:36,alimentación:{tipo:"herbivoro", comida:["frutos","brotes"]},habitat:"bosque tropical",secciones:"galeria", cantidad:7 },
         {   especie:"babuino",etiqueta:"mamiferos",familia:"cercopithecidae",duracion:41,alimentación:{tipo:"herbivoro", comida:["frutos","brotes","hojas"]},habitat:"pradera",secciones:"galeria", cantidad:8 },
         {   especie:"orangutan",etiqueta:"mamiferos",familia:"cercopithecidae",duracion:45,alimentación:{tipo:"omnivoro", comida:["frutos","bayas","hojas"]},habitat:"bosques",secciones:"galeria", cantidad:8 },
         {   especie:"macaco",etiqueta:"mamiferos",familia:"hominidae",duracion:45,alimentación:{tipo:"herbivoro", comida:["brotes","frutos","bayas"]},habitat:"bosques",secciones:"galeria", cantidad:9 },
         {   especie:"tigre",etiqueta:"mamiferos",familia:"felidae",duracion:10,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"selvas",secciones:"Selvado", cantidad:6 },
         {   especie:"leon",etiqueta:"mamiferos",familia:"felidae",duracion:15,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"sabana",secciones:"sabana", cantidad:11 },
         {   especie:"leopardo",etiqueta:"mamiferos",familia:"felidae",duracion:17,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"sabana",secciones:"sabana", cantidad:8 },
         {   especie:"guepardo",etiqueta:"mamiferos",familia:"felidae",duracion:12,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"sabana",secciones:"sabana", cantidad:7 },
         {   especie:"cebra",etiqueta:"mamiferos",familia:"equidae",duracion:30,alimentación:{tipo:"herbivoro", comida:["hierba","hojas"]},habitat:"sabana",secciones:"sabana", cantidad:5 },
         {   especie:"rinoceronte",etiqueta:"mamiferos",familia:"rinocerotidae",duracion:50,alimentación:{tipo:"herbivoro", comida:["hierba","hojas"]},habitat:"sabana",secciones:"sabana", cantidad:7 },
         {   especie:"hipopotamo",etiqueta:"mamiferos",familia:"hippopotamidae",duracion:50,alimentación:{tipo:["herbivoro"], comida:["hierba","hojas"]},habitat:"sabana",secciones:"sabana", cantidad:9 },
         {   especie:"oso pardo",etiqueta:"mamiferos",familia:"ursidae",duracion:30,alimentación:{tipo:"omnivoro", comida:["pescado","carne"]},habitat:"bosque",secciones:"rocas", cantidad:12 },
         {   especie:"oso panda",etiqueta:"mamiferos",familia:"ursidae",duracion:20,alimentación:{tipo:"omnivoro", comida:["bambu","bayas"]},habitat:"bosques",secciones:"rocas", cantidad:9 },
         {   especie:"oso polar",etiqueta:"mamiferos",familia:"ursidae",duracion:25,alimentación:{tipo:"carnivoro", comida:["carne","pescado"]},habitat:"nieve",secciones:"artico", cantidad:7 },
         {   especie:"oso negro",etiqueta:"mamiferos",familia:"ursidae",duracion:10,alimentación:{tipo:"omnivoro", comida:["hierba","bayas"]},habitat:"bosques",secciones:"rocas", cantidad:4 },
         {   especie:"foca",etiqueta:"mamiferos",familia:"phocidae",duracion:35,alimentación:{tipo:"carnivoro", comida:["pescado","carne"]},habitat:"nieve",secciones:"artico", cantidad:3 },
         {   especie:"leon marino",etiqueta:"mamiferos",familia:"otariidae",duracion:30,alimentación:{tipo:"carnivoro", comida:["pescado","carne"]},habitat:"nieve",secciones:"artico", cantidad:1 },
         {   especie:"lobo",etiqueta:"mamiferos",familia:"canidae",duracion:16,alimentación:{tipo:"carnivoro", comida:["carne","pescado"]},habitat:"bosques",secciones:"pradera", cantidad:6 },
         {   especie:"jirafa",etiqueta:"mamiferos",familia:"giraffidae",duracion:25,alimentación:{tipo:"herbivoro", comida:["hojas","brotes","bayas"]},habitat:"sabana",secciones:"sabana", cantidad:14 },
         {   especie:"elefantes",etiqueta:"mamiferos",familia:"elephantidae",duracion:70,alimentación:{tipo:"herbivoro", comida:["hojas"]},habitat:"sabana",secciones:"sabana", cantidad:11 },
         {   especie:"buitre",etiqueta:"aves",familia:"cathartidae",duracion:10,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"sabana",secciones:"sabana", cantidad:5 },
         {   especie:"quebrantahuesos",etiqueta:"aves",familia:"cathartidae",duracion:10,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"sabana",secciones:"sabana", cantidad:3 },
         {   especie:"aguila calva",etiqueta:"aves",familia:"accipitridae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"aviario", cantidad:3 },
         {   especie:"aguila real",etiqueta:"aves",familia:"accipitridae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"aviario", cantidad:3 },
         {   especie:"aguila imperial",etiqueta:"aves",familia:"accipitridae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"aviario", cantidad:8 },
         {   especie:"aguila cafre",etiqueta:"aves",familia:"accipitridae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"aviario", cantidad:5 },
         {   especie:"aguila harpia",etiqueta:"aves",familia:"accipitridae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"aviario", cantidad:2 },
         {   especie:"buho real",etiqueta:"aves",familia:"strigidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"bosque",secciones:"aviario", cantidad:5 },
         {   especie:"mochuelos",etiqueta:"aves",familia:"strigidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"bosque",secciones:"aviario", cantidad:4 },
         {   especie:"lechuzon gigante",etiqueta:"aves",familia:"strigidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"bosque",secciones:"aviario", cantidad:9 },
         {   especie:"buho antillano",etiqueta:"aves",familia:"strigidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"bosque",secciones:"aviario", cantidad:6 },
         {   especie:"guacamayo",etiqueta:"aves",familia:"psittacidae",duracion:13,alimentación:{tipo:"herbivoro", comida:["frutos","bayas"]},habitat:"bosque tropical",secciones:"aviario", cantidad:3 },
         {   especie:"guacamayo barbazul",etiqueta:"aves",familia:"psittacidae",duracion:13,alimentación:{tipo:"herbivoro", comida:["bayas","frutos"]},habitat:"bosque tropical",secciones:"aviario", cantidad:1 },
         {   especie:"guacamayo verde",etiqueta:"aves",familia:"psittacidae",duracion:13,alimentación:{tipo:"herbivoro", comida:["bayas"]},habitat:"bosque tropical",secciones:"aviario", cantidad:6 },
         {   especie:"guacamayo amarillo",etiqueta:"aves",familia:"psittacidae",duracion:13,alimentación:{tipo:"herbivoro", comida:["frutos"]},habitat:"bosque tropical",secciones:"aviario", cantidad:7 },
         {   especie:"tucan",etiqueta:"aves",familia:"ramphastidae",duracion:13,alimentación:{tipo:"herbivoro", comida:["frutos","bayas"]},habitat:"bosque tropical",secciones:"aviario", cantidad:6 },
         {   especie:"grulla",etiqueta:"aves",familia:"gruidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["semilla"]},habitat:"laguna",secciones:"aviario", cantidad:4 },
         {   especie:"flamenco",etiqueta:"aves",familia:"phoenicopteridae",duracion:27,alimentación:{tipo:"omnivoro", comida:["pescado"]},habitat:"laguna",secciones:"aviario", cantidad:1 },
         {   especie:"pato colorado",etiqueta:"aves",familia:"anatidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["pescado"]},habitat:"laguna",secciones:"aviario", cantidad:4 },
         {   especie:"pato cariblanco",etiqueta:"aves",familia:"anatidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["pescado"]},habitat:"laguna",secciones:"aviario", cantidad:5 },
         {   especie:"cisne negro",etiqueta:"aves",familia:"anatidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["pescado"]},habitat:"laguna",secciones:"aviario", cantidad:7 },
         {   especie:"cisne coscoraba",etiqueta:"aves",familia:"anatidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["pescado"]},habitat:"laguna",secciones:"aviario", cantidad:14 },
         {   especie:"tortuga",etiqueta:"reptiles",familia:"testudines",duracion:33,alimentación:{tipo:"omnivoro", comida:["pescado","algas"]},habitat:"acuatico",secciones:"acuario", cantidad:9 },
         {   especie:"cocodrilo",etiqueta:"reptiles",familia:"crocodylidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"rios",secciones:"estanque", cantidad:4 },
         {   especie:"caiman",etiqueta:"reptiles",familia:"crocodylidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"rios",secciones:"estanque", cantidad:5 },
         {   especie:"piton",etiqueta:"reptiles",familia:"serpentes",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"terrario", cantidad:3 },
         {   especie:"anaconda",etiqueta:"reptiles",familia:"serpentes",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"terrario", cantidad:2 },
         {   especie:"cobra",etiqueta:"reptiles",familia:"serpentes",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"terrario", cantidad:1 },
         {   especie:"vibora",etiqueta:"reptiles",familia:"serpentes",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"pradera",secciones:"terrario", cantidad:2 },
         {   especie:"rana punta de flecha",etiqueta:"anfibios",familia:"dendrobatidae",duracion:14,alimentación:{tipo:"omnivoro", comida:["insectos"]},habitat:"bosque tropical",secciones:"terrario", cantidad:7 },
         {   especie:"rana dardo dorada",etiqueta:"anfibios",familia:"dendrobatidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["carne"]},habitat:"bosque tropical",secciones:"terrario", cantidad:4 },
         {   especie:"salamandra gigante",etiqueta:"reptiles",familia:"anfibios",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"laguna",secciones:"terrario", cantidad:3 },
         {   especie:"tiburon blanco",etiqueta:"peces",familia:"lamnidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:1 },
         {   especie:"tiburon tigre",etiqueta:"peces",familia:"lamnidae",duracion:23,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:3 },
         {   especie:"tiburon toro",etiqueta:"peces",familia:"lamnidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:6 },
         {   especie:"tiburon ballena",etiqueta:"peces",familia:"lamnidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:9 },
         {   especie:"tiburon mako",etiqueta:"peces",familia:"lamnidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:4 },
         {   especie:"tiburon martillo",etiqueta:"peces",familia:"lamnidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:3 },
         {   especie:"manta raya",etiqueta:"peces",familia:"myliobatidae",duracion:13,alimentación:{tipo:"carnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:2 },
         {   especie:"damisela",etiqueta:"peces",familia:"molidae",duracion:33,alimentación:{tipo:"omnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:14, },
         {   especie:"pez payaso",etiqueta:"peces",familia:"molidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:1 },
         {   especie:"pez cirujano",etiqueta:"peces",familia:"molidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:4 },
         {   especie:"pez angel parador",etiqueta:"peces",familia:"molidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:5 },
         {   especie:"gobios",etiqueta:"peces",familia:"molidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:3 },
         {   especie:"perca enana",etiqueta:"peces",familia:"molidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:3 },
         {   especie:"pez luna",etiqueta:"peces",familia:"molidae",duracion:13,alimentación:{tipo:"omnivoro", comida:["carne"]},habitat:"oceano",secciones:"acuario", cantidad:4 },
        ])
    
db.animalconcreto.insertMany([
    {

     especie:"gorila",
     etiqueta:"mamiferos",
     familia:"hominidae",
     enfermedad: false,
     nacimiento: new Date("2007-05-16"),
     habitat:"bosque tropical",
     secciones:"galeria"},
     {   especie:"chimpance",etiqueta:"mamiferos",familia:"hominidae",enfermedad: true ,nacimiento: new Date("2001-10-01"),habitat:"bosque tropical",secciones:"galeria" },
     {   especie:"mandril",etiqueta:"mamiferos",familia:"cercopithecidae",enfermedad: true, nacimiento: new Date("2001-10-01"),habitat:"bosque tropical",secciones:"galeria" },
     {   especie:"babuino",etiqueta:"mamiferos",familia:"cercopithecidae",enfermedad: false ,nacimiento: new Date("2001-10-01"),habitat:"pradera",secciones:"galeria" },
     {   especie:"orangutan",etiqueta:"mamiferos",familia:"cercopithecidae",enfermedad: true ,nacimiento: new Date("1999-09-09"),habitat:"bosques",secciones:"galeria"},
     {   especie:"macaco",etiqueta:"mamiferos",familia:"hominidae",enfermedad: true ,nacimiento: new Date("1983-08-13"),habitat:"bosques",secciones:"galeria"},
     {   especie:"tigre",etiqueta:"mamiferos",familia:"felidae",enfermedad: false ,nacimiento: new Date("2016-09-02"),habitat:"selvas",secciones:"Selvado" },
     {   especie:"leon",etiqueta:"mamiferos",familia:"felidae",enfermedad: false ,nacimiento: new Date("2011-04-31"),habitat:"sabana",secciones:"sabana" },
     {   especie:"leopardo",etiqueta:"mamiferos",familia:"felidae",enfermedad: true ,nacimiento: new Date("2009-11-11"),habitat:"sabana",secciones:"sabana" },
     {   especie:"guepardo",etiqueta:"mamiferos",familia:"felidae",enfermedad: false ,nacimiento: new Date("2010-10-17"),habitat:"sabana",secciones:"sabana" },
     {   especie:"cebra",etiqueta:"mamiferos",familia:"equidae",enfermedad: true ,nacimiento: new Date("2000-12-03"),habitat:"sabana",secciones:"sabana" },
     {   especie:"rinoceronte",etiqueta:"mamiferos",familia:"rinocerotidae",enfermedad: false ,nacimiento: new Date("1979-06-02"),habitat:"sabana",secciones:"sabana" },
     {   especie:"hipopotamo",etiqueta:"mamiferos",familia:"hippopotamidae",enfermedad: true ,nacimiento: new Date("1981-10-28"),habitat:"sabana",secciones:"sabana" },
     {   especie:"oso pardo",etiqueta:"mamiferos",familia:"ursidae",enfermedad: true ,nacimiento: new Date("1998-02-04"),habitat:"bosque",secciones:"rocas"},
     {   especie:"oso panda",etiqueta:"mamiferos",familia:"ursidae",enfermedad: false ,nacimiento: new Date("2007-07-20"),habitat:"bosques",secciones:"rocas" },
     {   especie:"oso polar",etiqueta:"mamiferos",familia:"ursidae",enfermedad: true ,nacimiento: new Date("1995-05-13"),habitat:"nieve",secciones:"artico" },
     {   especie:"oso negro",etiqueta:"mamiferos",familia:"ursidae",enfermedad: true ,nacimiento: new Date("2019-04-07"),habitat:"bosques",secciones:"rocas" },
     {   especie:"foca",etiqueta:"mamiferos",familia:"phocidae",enfermedad: true ,nacimiento: new Date("1988-01-05"),habitat:"nieve",secciones:"artico" },
     {   especie:"leon marino",etiqueta:"mamiferos",familia:"otariidae",enfermedad: true ,nacimiento: new Date("1992-12-14"),habitat:"nieve",secciones:"artico" },
     {   especie:"lobo",etiqueta:"mamiferos",familia:"canidae",enfermedad: false ,nacimiento: new Date("2015-04-18"),habitat:"bosques",secciones:"pradera" },
     {   especie:"jirafa",etiqueta:"mamiferos",familia:"giraffidae",enfermedad: false ,nacimiento: new Date("2003-06-14"),habitat:"sabana",secciones:"sabana" },
     {   especie:"elefantes",etiqueta:"mamiferos",familia:"elephantidae",enfermedad: true ,nacimiento: new Date("2006-08-12"),habitat:"sabana",secciones:"sabana" },
     {   especie:"buitre",etiqueta:"aves",familia:"cathartidae",enfermedad: true ,nacimiento: new Date("2002-01-11"),habitat:"sabana",secciones:"sabana" },
     {   especie:"quebrantahuesos",etiqueta:"aves",familia:"cathartidae",enfermedad: false ,nacimiento: new Date("2014-09-24"),habitat:"sabana",secciones:"sabana" },
     {   especie:"aguila calva",etiqueta:"aves",familia:"accipitridae",enfermedad: true ,nacimiento: new Date("2001-04-14"),habitat:"pradera",secciones:"aviario" },
     {   especie:"aguila real",etiqueta:"aves",familia:"accipitridae",enfermedad: false ,nacimiento: new Date("2004-05-11"),habitat:"pradera",secciones:"aviario" },
     {   especie:"aguila imperial",etiqueta:"aves",familia:"accipitridae",enfermedad: true ,nacimiento: new Date("2005-01-11"),habitat:"pradera",secciones:"aviario" },
     {   especie:"aguila cafre",etiqueta:"aves",familia:"accipitridae",enfermedad: false ,nacimiento: new Date("2009-09-18"),habitat:"pradera",secciones:"aviario" },
     {   especie:"aguila harpia",etiqueta:"aves",familia:"accipitridae",enfermedad: true ,nacimiento: new Date("1997-12-12"),habitat:"pradera",secciones:"aviario" },
     {   especie:"buho real",etiqueta:"aves",familia:"strigidae",enfermedad: true ,nacimiento: new Date("1998-12-31"),habitat:"bosque",secciones:"aviario" },
     {   especie:"mochuelos",etiqueta:"aves",familia:"strigidae",enfermedad: false ,nacimiento: new Date("1993-05-13"),habitat:"bosque",secciones:"aviario" },
     {   especie:"lechuzon gigante",etiqueta:"aves",familia:"strigidae",enfermedad: false ,nacimiento: new Date("2014-06-15"),habitat:"bosque",secciones:"aviario" },
     {   especie:"buho antillano",etiqueta:"aves",familia:"strigidae",enfermedad: true ,nacimiento: new Date("2012-10-28"),habitat:"bosque",secciones:"aviario" },
     {   especie:"guacamayo",etiqueta:"aves",familia:"psittacidae",enfermedad: true ,nacimiento: new Date("2003-02-28"),habitat:"bosque tropical",secciones:"aviario" },
     {   especie:"guacamayo barbazul",etiqueta:"aves",familia:"psittacidae",enfermedad: false ,nacimiento: new Date("2011-11-11"),habitat:"bosque tropical",secciones:"aviario" },
     {   especie:"guacamayo verde",etiqueta:"aves",familia:"psittacidae",enfermedad: true ,nacimiento: new Date("2014-04-30"),habitat:"bosque tropical",secciones:"aviario", },
     {   especie:"guacamayo amarillo",etiqueta:"aves",familia:"psittacidae",enfermedad: false ,nacimiento: new Date("2004-08-19"),habitat:"bosque tropical",secciones:"aviario" },
     {   especie:"tucan",etiqueta:"aves",familia:"ramphastidae",enfermedad: true ,nacimiento: new Date("2003-03-25"),habitat:"bosque tropical",secciones:"aviario" },
     {   especie:"grulla",etiqueta:"aves",familia:"gruidae",enfermedad: true ,nacimiento: new Date("2003-11-04"),habitat:"laguna",secciones:"aviario"},
     {   especie:"flamenco",etiqueta:"aves",familia:"phoenicopteridae",enfermedad: true ,nacimiento: new Date("1999-06-14"),habitat:"laguna",secciones:"aviario" },
     {   especie:"pato colorado",etiqueta:"aves",familia:"anatidae",enfermedad: true ,nacimiento: new Date("2006-07-13"),habitat:"laguna",secciones:"aviario" },
     {   especie:"pato cariblanco",etiqueta:"aves",familia:"anatidae",enfermedad: true ,nacimiento: new Date("2003-04-12"),habitat:"laguna",secciones:"aviario" },
     {   especie:"cisne negro",etiqueta:"aves",familia:"anatidae",enfermedad: false ,nacimiento: new Date("2012-07-09"),habitat:"laguna",secciones:"aviario" },
     {   especie:"cisne coscoraba",etiqueta:"aves",familia:"anatidae",enfermedad: false ,nacimiento: new Date("2007-05-21"),habitat:"laguna",secciones:"aviario" },
     {   especie:"tortuga",etiqueta:"reptiles",familia:"testudines",enfermedad: false ,nacimiento: new Date("2013-04-20"),habitat:"acuatico",secciones:"acuario" },
     {   especie:"cocodrilo",etiqueta:"reptiles",familia:"crocodylidae",enfermedad: false  ,nacimiento: new Date("2015-09-17"),habitat:"rios",secciones:"estanque" },
     {   especie:"caiman",etiqueta:"reptiles",familia:"crocodylidae",enfermedad: false ,nacimiento: new Date("2012-01-01"),habitat:"rios",secciones:"estanque" },
     {   especie:"piton",etiqueta:"reptiles",familia:"serpentes",enfermedad: true ,nacimiento: new Date("2021-11-14"),habitat:"pradera",secciones:"terrario" },
     {   especie:"anaconda",etiqueta:"reptiles",familia:"serpentes",enfermedad: true ,nacimiento: new Date("2018-04-19"),habitat:"pradera",secciones:"terrario" },
     {   especie:"cobra",etiqueta:"reptiles",familia:"serpentes",enfermedad: false ,nacimiento: new Date("2020-02-20"),habitat:"pradera",secciones:"terrario" },
     {   especie:"vibora",etiqueta:"reptiles",familia:"serpentes",enfermedad: false ,nacimiento: new Date("2014-08-05"),habitat:"pradera",secciones:"terrario" },
     {   especie:"rana punta de flecha",etiqueta:"anfibios",familia:"dendrobatidae",enfermedad: true ,nacimiento: new Date("2012-07-11"),habitat:"bosque tropical",secciones:"terrario" },
     {   especie:"rana dardo dorada",etiqueta:"anfibios",familia:"dendrobatidae",enfermedad: false ,nacimiento: new Date("2015-05-11"),habitat:"bosque tropical",secciones:"terrario" },
     {   especie:"salamandra gigante",etiqueta:"reptiles",familia:"anfibios",enfermedad: true ,nacimiento: new Date("2011-07-23"),habitat:"laguna",secciones:"terrario" },
     {   especie:"tiburon blanco",etiqueta:"peces",familia:"lamnidae",enfermedad: true ,nacimiento: new Date("2006-06-06"),habitat:"oceano",secciones:"acuario" },
     {   especie:"tiburon tigre",etiqueta:"peces",familia:"lamnidae",enfermedad: true ,nacimiento: new Date("2000-03-12"),habitat:"oceano",secciones:"acuario" },
     {   especie:"tiburon toro",etiqueta:"peces",familia:"lamnidae",enfermedad: true ,nacimiento: new Date("1998-07-15"),habitat:"oceano",secciones:"acuario" },
     {   especie:"tiburon ballena",etiqueta:"peces",familia:"lamnidae",enfermedad: false ,nacimiento: new Date("2002-04-01"),habitat:"oceano",secciones:"acuario" },
     {   especie:"tiburon mako",etiqueta:"peces",familia:"lamnidae",enfermedad: false ,nacimiento: new Date("2001-04-08"),habitat:"oceano",secciones:"acuario" },
     {   especie:"tiburon martillo",etiqueta:"peces",familia:"lamnidae",enfermedad: true ,nacimiento: new Date("2014-04-15"),habitat:"oceano",secciones:"acuario" },
     {   especie:"manta raya",etiqueta:"peces",familia:"myliobatidae",enfermedad: false ,nacimiento: new Date("2003-02-27"),habitat:"oceano",secciones:"acuario"},
     {   especie:"damisela",etiqueta:"peces",familia:"molidae",enfermedad: true ,nacimiento: new Date("2003-01-03"),habitat:"oceano",secciones:"acuario" },
     {   especie:"pez payaso",etiqueta:"peces",familia:"molidae",enfermedad: true ,nacimiento: new Date("2004-05-14"),habitat:"oceano",secciones:"acuario" },
     {   especie:"pez cirujano",etiqueta:"peces",familia:"molidae",enfermedad: false ,nacimiento: new Date("2015-01-11"),habitat:"oceano",secciones:"acuario"},
     {   especie:"pez angel parador",etiqueta:"peces",familia:"molidae",enfermedad: false ,nacimiento: new Date("2019-06-14"),habitat:"oceano",secciones:"acuario" },
     {   especie:"gobios",etiqueta:"peces",familia:"molidae",enfermedad: false ,nacimiento: new Date("2019-04-18"),habitat:"oceano",secciones:"acuario" },
     {   especie:"perca enana",etiqueta:"peces",familia:"molidae",enfermedad: true ,nacimiento: new Date("2021-06-24"),habitat:"oceano",secciones:"acuario" },
     {   especie:"pez luna",etiqueta:"peces",familia:"molidae",enfermedad: true ,nacimiento: new Date("2020-12-04"),habitat:"oceano",secciones:"acuario" },
    ])


